# Generated by Django 5.2 on 2025-11-02 13:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hoppr_study_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('dicom_file', models.FileField(upload_to='dicoms/')),
                ('patient_history', models.TextField()),
                ('visit_reason', models.TextField()),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('escalated', 'Escalated')], default='uploaded', max_length=20)),
                ('urgency', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], max_length=20, null=True)),
                ('clinical_report', models.TextField(blank=True, null=True)),
                ('patient_summary', models.TextField(blank=True, null=True)),
                ('findings_json', models.JSONField(blank=True, default=dict)),
                ('workflow_log', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_name', models.CharField(max_length=255)),
                ('model_id', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('threshold_used', models.FloatField()),
                ('is_present', models.BooleanField()),
                ('confidence_level', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='agents.study')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
