from typing import Dict
from groq import Groq


class ReportGenerator:
    """Generates final report with different templates based on urgency"""
    
    def __init__(self, groq: Groq):
        self.groq = groq
    
    def generate(self, findings: Dict, vlm: str, context: Dict, urgency: str, action: str) -> str:
        
        findings_text = [f"{name}: {data['score']:.2f}" 
                        for name, data in findings.items() 
                        if data['score'] > data.get('threshold_used', 0.5)]
        
        # Different prompt based on urgency
        if urgency == "critical" or action == "ESCALATE":
            report_type = "URGENT/CRITICAL report with immediate recommendations"
            extra_instruction = "Clearly highlight CRITICAL findings at the top. Recommend immediate follow-up."
        elif urgency == "high":
            report_type = "HIGH-PRIORITY report with expedited recommendations"
            extra_instruction = "Emphasize significant findings and suggest timely follow-up."
        else:
            report_type = "STANDARD radiology report"
            extra_instruction = "Provide thorough but routine analysis."
        
        prompt = f"""Generate a {report_type}.

Patient: {context['history']}
Indication: {context['reason']}

Classification Results:
{chr(10).join(findings_text) if findings_text else 'No significant findings'}

VLM Description:
{vlm}

{extra_instruction}

Create a structured report with:
1. CLINICAL INDICATION
2. FINDINGS (highlight any critical findings)
3. IMPRESSION
4. RECOMMENDATIONS (urgency-appropriate)"""
        
        try:
            response = self.groq.chat.completions.create(
                model="llama-3.3-70b-versatile",
                messages=[
                    {"role": "system", "content": "You are a radiologist."},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.3
            )
            
            report = response.choices[0].message.content
            return report
            
        except Exception as e:
            return "Report generation failed"
    
    def generate_emergency(self, findings: Dict, context: Dict) -> str:
        """Emergency report - skip the LLM, just format critical info"""
        
        critical = [f"{name} (confidence: {data['score']:.2f})" 
                   for name, data in findings.items() 
                   if data['score'] > 0.75]
        
        report = f"""
╔══════════════════════════════════════════════════════════════╗
║                    ⚠️  CRITICAL ALERT ⚠️                      ║
╚══════════════════════════════════════════════════════════════╝

PATIENT: {context['history']}
INDICATION: {context['reason']}

🚨 CRITICAL FINDINGS DETECTED:
{chr(10).join('  • ' + f for f in critical)}

⚡ IMMEDIATE ACTION REQUIRED:
  • Radiologist review STAT
  • Consider urgent clinical correlation
  • Patient monitoring recommended

📋 PRELIMINARY AUTOMATED ANALYSIS
This is a preliminary report generated by AI due to detection of 
critical findings. A board-certified radiologist should review 
immediately.

⏰ Report Generated: EMERGENCY PROTOCOL ACTIVATED
"""
        return report
        
class PatientSummaryGenerator:
    """Generates patient-friendly explanations (HIPAA-compliant, appropriate language)"""
    
    def __init__(self, groq: Groq):
        self.groq = groq

    def generate_patient_summary(self, findings: Dict, urgency: str, action: str, 
                                 clinical_report: str) -> str:
        """
        Generate a patient-appropriate summary
        
        HIPAA Considerations:
        - No unnecessary medical jargon
        - Honest but not alarming
        - Emphasize need for doctor discussion
        - Don't diagnose - describe findings
        - Provide context and next steps
        """
        
        findings_text = [f"{name}" for name, data in findings.items() 
                        if data['score'] > 0.5]
        
        # Different approach based on urgency
        if urgency == "critical" or action == "ESCALATE":
            tone = "clear and direct but supportive"
            emphasis = "Your care team has been notified and will discuss these findings with you promptly."
        elif urgency == "high":
            tone = "informative and measured"
            emphasis = "Your doctor will want to discuss these findings with you soon."
        else:
            tone = "reassuring and educational"
            emphasis = "Your doctor will review these results with you at your next appointment."
        
        prompt = f"""You are writing a patient-facing summary of a chest X-ray.

FINDINGS DETECTED:
{chr(10).join(findings_text) if findings_text else 'No significant abnormalities'}

URGENCY LEVEL: {urgency}

GUIDELINES:
1. Use plain language - avoid medical jargon or explain it simply
2. Be honest about what was found, but don't alarm unnecessarily
3. DON'T make diagnoses - describe findings only
4. Emphasize that a doctor will review and explain in detail
5. Provide context (e.g., "This is a common finding that...")
6. Include appropriate next steps
7. Be {tone}
8. Keep it under 150 words

Structure:
- What We Saw: Brief description of findings in plain language
- What This Might Mean: General context (not diagnosis)
- Next Steps: What will happen next
- Remember: {emphasis}

Write the patient summary now:"""
        
        try:
            response = self.groq.chat.completions.create(
                model="llama-3.3-70b-versatile",
                messages=[
                    {
                        "role": "system", 
                        "content": "You are a patient advocate helping explain medical findings clearly and compassionately. Never diagnose. Always emphasize doctor involvement."
                    },
                    {"role": "user", "content": prompt}
                ],
                temperature=0.5  # Slightly higher for more natural language
            )
            
            summary = response.choices[0].message.content
            return summary
            
        except Exception as e:
            # Fallback to safe default message
            return self._generate_safe_fallback(urgency)
    
    def _generate_safe_fallback(self, urgency: str) -> str:
        """Safe fallback message if LLM fails"""
        if urgency in ["critical", "high"]:
            return """
Your chest X-ray has been completed. Our imaging system has identified some findings 
that your doctor will want to discuss with you. Your care team has been notified and 
will reach out to you to explain the results and discuss any necessary next steps.

If you have urgent symptoms or concerns, please contact your healthcare provider 
or seek immediate medical attention.
"""
        else:
            return """
Your chest X-ray has been completed. The images have been analyzed and will be 
reviewed by your doctor, who will discuss the results with you at your next 
appointment.

If you have any questions or concerns before then, please don't hesitate to 
contact your healthcare provider.
"""