import React from "react";
import "./healthcare-landing.css";

export default function DoctorDemo() {
  return (
    <div className="demo-root">
      <header className="demo-header">
        <h1>Doctor Dashboard</h1>
        <p>Review patient scans and AI-assisted reports</p>
      </header>

      <main className="demo-container grid-2">
        <section className="demo-card">
          <h2>Patient Overview</h2>
          <ul>
            <li>Abdul Khan — No critical findings</li>
            <li>John Doe — Mild cardiomegaly detected</li>
            <li>Sara Ali — Possible pleural effusion</li>
          </ul>
        </section>

        <section className="demo-card">
          <h2>AI Risk Predictions</h2>
          <p>
            <strong>Pneumothorax :</strong> 2% | 
            <strong>Cardiomegaly :</strong> 8% | 
            <strong>Effusion :</strong> 3%
          </p>
          <p>
            Results generated by Hoppr AI VLM model – review and confirm before
            diagnosis.
          </p>
        </section>
      </main>
    </div>
  );
}
